apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "mypythonapplication2641"

  links:
    - url: https://github.com/RohanAwasthi/aws-elastic beanstalk-20240208101659
      title: "mypythonapplication2641"
      icon: code

  labels:
    system: web-apps
    trackid: "aws-elastic beanstalk-20240208101659"
    environmentname: mypythonenvironment1

  tags:
    - java
    - aws
    - "applicationtype-webapplication"

  annotations:
    # add elastic beanstalk annotation
    jenkins.io/github-folder: 'custom-actions/tf-mypythonapplication2641'
    github.com/project-slug: RohanAwasthi/aws-elastic beanstalk-20240208101659
    backstage.io/techdocs-ref: dir:.
    backstage.io/linguist: https://github.com/ItRachii/spring-boot-ebs
    sonarqube.org/project-key: 'demo-app/aws-elb-java'

spec:
  type: service
  lifecycle: experimental
  system: elasticbeanstalk
  owner: "group:default/ey"
